[SteamClient]
# Relative or absolute path to the game's exe
exe=Game.exe
# Optional: working directory for the exe (leave empty for exe's directory)
ExeRunDir=
# Optional: command line arguments
ExeCommandLine=
# Steam AppID
AppId=

# path to the steamclient dlls, both must be set, absolute paths or relative to the loader directory
SteamClientDll=steamclient.dll
SteamClient64Dll=steamclient64.dll

[Injection]
# force inject steamclient dll instead of waiting for the app to load it
ForceInjectSteamClient=0

# force inject GameOverlayRenderer dll instead of waiting for the app to load it
ForceInjectGameOverlayRenderer=0

# path to a folder containing some dlls to inject into the app upon start, DllsToInjectFolder=extra_dlls
DllsToInjectFolder=

# don't display an error message when a dll injection fails
IgnoreInjectionError=1

# don't display an error message if the architecture of the loader is different from the app
IgnoreLoaderArchDifference=0

[Persistence]
# Persistence mode: 0=disabled, 1=loader spawns .exe, 2=loader does not spawn .exe
SteamClientRemainLoaded=0

[Debug]
# Enable debug logging (0=disabled, 1=enabled)
ResumeByDebugger=0